config/routes.rb
HackerNewsClone::Application.routes.draw do
  devise_for :users

  root :to => 'links#index'

  resources :links, only: [:index, :new, :create, :show, :edit, :update] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :update, :edit]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment_text, :link_id, :user_id
  belongs_to :link
  belongs_to :user
  validates :user_id,
    :presence => { :message => "You must be signed in to comment." }

  def can_edit?
    Time.now - 15.minutes < created_at
  end 
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url
  validates_uniqueness_of :url
  belongs_to :user
  has_many :comments
  has_many :votes

  def vote_count
    self.votes.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :links
  has_many :comments
  has_many :votes

  def already_voted?(link)
    self.votes.by_link(link).exists?
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :link_id, :user_id

  belongs_to :user
  belongs_to :link

  def self.by_link(link)
    where(:link_id => link)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.build(params[:comment])
    #@comment.user_id = current_user.id
    @comment.user_id = current_user.id if current_user
    if @comment.save
      flash[:notice] = "Successfully submitted #{@link.title}"
      redirect_to @link
    else
      render 'links/show'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to link_path(@comment.link)
      flash[:notice] = "Successfully edited your comment."
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if params[:order]
      @links = Link.joins('LEFT JOIN votes ON votes.link_id = links.id GROUP BY links.id ORDER BY COUNT(*) DESC')
    else
      @links = Link.all
    end
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(params[:link])
    @link.user_id = current_user.id
    if @link.save
      redirect_to links_path
      flash[:notice] = "Successfully submitted #{@link.title}"
    else
      flash[:notice] = "This link has already been submitted"
      render 'new'
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(params[:link])
      redirect_to links_path
      flash[:notice] = "Successfully edited #{@link.title}"
    else
      flash[:notice] = "This link has already been submitted"
      render 'edit'
    end
  end

  def show
    @link = Link.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = Vote.new(:link_id => params[:link_id], :user_id => current_user.id)

    if @vote.save
      redirect_to '/'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/edit.html.erb
<%= form_for @comment, :url => link_comment_path(params[:link_id], @comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :comment_text %>
  </p>
    <%= f.text_area :comment_text %>
  
    <%= f.submit "Update comment" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNewsClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="account">
<% if current_user %>
  <span>Welcome, <%= current_user.email %></span>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>
  
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= link_to "Submit", new_link_path %>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<%= form_for @link do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :url %>
  <%= f.text_field :url %>
</p>
<p>
  <%= f.submit "Save" %>
</p>
<% end %>

app/views/links/index.html.erb
<%= link_to "ORDER BY VOTES", links_path(:order => true) %>

<% @links.each do |link| %>
<p>
  <%= link_to link.title, link_path(link.id) %> |
  <%= link_to "#{link.url}", link.url %> |
  <% if link.user == current_user %>
    <%= link_to "Edit Link", edit_link_path(link) %>
  <% end %>
  
  <% if current_user && link.user_id != current_user.id && !current_user.already_voted?(link.id) %>
    <%= link_to "^", link_votes_path(link), :method => :post %>
  <% end %>
</p>
<% end %>

app/views/links/new.html.erb
<%= form_for @link do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :url %>
  <%= f.text_field :url %>
</p> 
<p>
  <%= f.submit "Submit link" %>
</p>
<% end %>

app/views/links/show.html.erb
<p>
  <%= @link.title %> | <%= link_to @link.url, @link.url %>
</p>

<p>
  <% @link.comments.each do |comment| %>
  <p>
    <% if comment.persisted? %>
      <%= comment.user.email %><br>
      <%= comment.comment_text %>
      <%= link_to_if(current_user && comment.can_edit?, "Edit", edit_link_comment_path(@link, comment)){} %>
    <% end %>
  </p>
  <% end %>
  
<%= form_for [@link, @comment ||= Comment.new] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :comment_text %>
  </p>
    <%= f.text_area :comment_text %>
  
    <%= f.submit "Submit comment" %>

<% end %>